// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: echo.proto

package echo

import (
	_ "github.com/95933447/grpcgateway/example/client/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Nil     ErrCode = 0
	ErrCode_ErrFail ErrCode = 1001
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "Nil",
		1001: "ErrFail",
	}
	ErrCode_value = map[string]int32{
		"Nil":     0,
		"ErrFail": 1001,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_echo_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_echo_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{0}
}

type EchoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Echo          string                 `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoReq) Reset() {
	*x = EchoReq{}
	mi := &file_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReq) ProtoMessage() {}

func (x *EchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReq.ProtoReflect.Descriptor instead.
func (*EchoReq) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoReq) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

type EchoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Echo          string                 `protobuf:"bytes,2,opt,name=echo,proto3" json:"echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResp) Reset() {
	*x = EchoResp{}
	mi := &file_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResp) ProtoMessage() {}

func (x *EchoResp) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResp.ProtoReflect.Descriptor instead.
func (*EchoResp) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResp) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

var File_echo_proto protoreflect.FileDescriptor

const file_echo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"echo.proto\x12\x04echo\x1a\text.proto\"\x1d\n" +
	"\aEchoReq\x12\x12\n" +
	"\x04echo\x18\x01 \x01(\tR\x04echo\"\x1e\n" +
	"\bEchoResp\x12\x12\n" +
	"\x04echo\x18\x02 \x01(\tR\x04echo* \n" +
	"\aErrCode\x12\a\n" +
	"\x03Nil\x10\x00\x12\f\n" +
	"\aErrFail\x10\xe9\a2\xe1\x01\n" +
	"\x04Echo\x126\n" +
	"\tBasicEcho\x12\r.echo.EchoReq\x1a\x0e.echo.EchoResp\"\n" +
	"\x8a\xb5\x18\x06\n" +
	"\x04POST\x128\n" +
	"\n" +
	"NoAuthEcho\x12\r.echo.EchoReq\x1a\x0e.echo.EchoResp\"\v\x8a\xb5\x18\a\n" +
	"\x03GET\x10\x01\x12;\n" +
	"\rNoAuthEchoErr\x12\r.echo.EchoReq\x1a\x0e.echo.EchoResp\"\v\x8a\xb5\x18\a\n" +
	"\x03GET\x10\x01\x12*\n" +
	"\tInnerEcho\x12\r.echo.EchoReq\x1a\x0e.echo.EchoRespB\rZ\vclient/echob\x06proto3"

var (
	file_echo_proto_rawDescOnce sync.Once
	file_echo_proto_rawDescData []byte
)

func file_echo_proto_rawDescGZIP() []byte {
	file_echo_proto_rawDescOnce.Do(func() {
		file_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)))
	})
	return file_echo_proto_rawDescData
}

var file_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_proto_goTypes = []any{
	(ErrCode)(0),     // 0: echo.ErrCode
	(*EchoReq)(nil),  // 1: echo.EchoReq
	(*EchoResp)(nil), // 2: echo.EchoResp
}
var file_echo_proto_depIdxs = []int32{
	1, // 0: echo.Echo.BasicEcho:input_type -> echo.EchoReq
	1, // 1: echo.Echo.NoAuthEcho:input_type -> echo.EchoReq
	1, // 2: echo.Echo.NoAuthEchoErr:input_type -> echo.EchoReq
	1, // 3: echo.Echo.InnerEcho:input_type -> echo.EchoReq
	2, // 4: echo.Echo.BasicEcho:output_type -> echo.EchoResp
	2, // 5: echo.Echo.NoAuthEcho:output_type -> echo.EchoResp
	2, // 6: echo.Echo.NoAuthEchoErr:output_type -> echo.EchoResp
	2, // 7: echo.Echo.InnerEcho:output_type -> echo.EchoResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_proto_init() }
func file_echo_proto_init() {
	if File_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_proto_goTypes,
		DependencyIndexes: file_echo_proto_depIdxs,
		EnumInfos:         file_echo_proto_enumTypes,
		MessageInfos:      file_echo_proto_msgTypes,
	}.Build()
	File_echo_proto = out.File
	file_echo_proto_goTypes = nil
	file_echo_proto_depIdxs = nil
}
